import 'package:flutter/material.dart';

class Product {
  final String? image, title, origin, description;
  final int? price, id;
  final Color? color;

  Product({
    this.id,
    this.image,
    this.title,
    this.price,
    this.origin,
    this.description,
    this.color,
  });
}

List<Product> products = [
  Product(
      id: 1,
      title: "Valentines Items",
      price: 399,
      origin: "BD",
      description: dummyText,
      image: "assets/images/1.png",
      color: Color(0xFF6F787D)),
  Product(
      id: 2,
      title: "Rose Gifts",
      price: 265,
      origin: "USA",
      description: dummyText,
      image: "assets/images/2.png",
      color: Color(0xFF141518)),
  Product(
      id: 3,
      title: "Doll",
      price: 540,
      origin: "CN",
      description: dummyText,
      image: "assets/images/3.png",
      color: Color(0xFF712C1D)),
  Product(
      id: 4,
      title: "Gift",
      price: 299,
      origin: "BD",
      description: dummyText,
      image: "assets/images/4.png",
      color: Color(0xFFAA220A)),
  Product(
      id: 5,
      title: "Rose",
      price: 599,
      origin: "USA",
      description: dummyText,
      image: "assets/images/5.png",
      color: Color(0xFFF80205)),
  Product(
    id: 6,
    title: "Toy",
    price: 850,
    origin: "IND",
    description: dummyText,
    image: "assets/images/6.png",
    color: Color(0xFF6A035B),
  ),
  Product(
    id: 7,
    title: "House",
    price: 199,
    origin: "BD",
    description: dummyText,
    image: "assets/images/7.png",
    color: Color(0xFF5327E0),
  ),
  Product(
    id: 8,
    title: "Red Rose",
    price: 299,
    origin: "BD",
    description: dummyText,
    image: "assets/images/8.png",
    color: Color(0xFF63D3FA),
  ),
  Product(
    id: 9,
    title: "Purple Rose",
    price: 250,
    origin: "USA",
    description: dummyText,
    image: "assets/images/9.png",
    color: Color(0xFF03381B),
  ),
  Product(
    id: 10,
    title: "Shopics",
    price: 599,
    origin: "CN",
    description: dummyText,
    image: "assets/images/10.png",
    color: Color(0xFF139F02),
  ),
  Product(
    id: 799,
    title: "Key Ring",
    price: 500,
    origin: "CN",
    description: dummyText,
    image: "assets/images/11.png",
    color: Color(0xFFC90F04),
  ),
  Product(
    id: 12,
    title: "Teddy Bear",
    price: 620,
    origin: "USA",
    description: dummyText,
    image: "assets/images/12.png",
    color: Color(0xFF0178C7),
  ),
  Product(
    id: 13,
    title: "Boy/Girl",
    price: 255,
    origin: "CN",
    description: dummyText,
    image: "assets/images/13.png",
    color: Color(0xFFD62862),
  ),
  Product(
    id: 14,
    title: "Golden Rose",
    price: 499,
    origin: "BD",
    description: dummyText,
    image: "assets/images/14.png",
    color: Color(0xFFFE5200),
  ),
  Product(
      id: 15,
      title: "Valentines Items",
      price: 259,
      origin: "BD",
      description: dummyText,
      image: "assets/images/1.png",
      color: Color(0xFFCCB28D)),
  Product(
      id: 16,
      title: "Rose Gifts",
      price: 399,
      origin: "USA",
      description: dummyText,
      image: "assets/images/2.png",
      color: Color(0xFFF5E773)),
  Product(
      id: 17,
      title: "Doll",
      price: 499,
      origin: "CN",
      description: dummyText,
      image: "assets/images/3.png",
      color: Color(0xFF9ABD44)),
  Product(
      id: 18,
      title: "Gift",
      price: 699,
      origin: "BD",
      description: dummyText,
      image: "assets/images/4.png",
      color: Color(0xFF70E66C)),
  Product(
      id: 19,
      title: "Rose",
      price: 250,
      origin: "USA",
      description: dummyText,
      image: "assets/images/5.png",
      color: Color(0xFFFB7883)),
  Product(
    id: 20,
    title: "Toy",
    price: 199,
    origin: "IND",
    description: dummyText,
    image: "assets/images/6.png",
    color: Color(0xFFBA855A),
  ),
  Product(
    id: 21,
    title: "House",
    price: 175,
    origin: "BD",
    description: dummyText,
    image: "assets/images/7.png",
    color: Color(0xFFF7EF8D),
  ),
  Product(
    id: 22,
    title: "Red Rose",
    price: 278,
    origin: "BD",
    description: dummyText,
    image: "assets/images/8.png",
    color: Color(0xFFF7EF8D),
  ),
  Product(
    id: 23,
    title: "Purple Rose",
    price: 499,
    origin: "USA",
    description: dummyText,
    image: "assets/images/9.png",
    color: Color(0xFFF2B576),
  ),
  Product(
    id: 24,
    title: "Shopics",
    price: 375,
    origin: "CN",
    description: dummyText,
    image: "assets/images/10.png",
    color: Color(0xFFF2B576),
  ),
  Product(
    id: 25,
    title: "Key Ring",
    price: 699,
    origin: "CN",
    description: dummyText,
    image: "assets/images/11.png",
    color: Color(0xFFE26B40),
  ),
  Product(
    id: 26,
    title: "Teddy Bear",
    price: 775,
    origin: "USA",
    description: dummyText,
    image: "assets/images/12.png",
    color: Color(0xFFEB9392),
  ),
  Product(
    id: 27,
    title: "Boy/Girl",
    price: 675,
    origin: "CN",
    description: dummyText,
    image: "assets/images/13.png",
    color: Color(0xFFEB9392),
  ),
  Product(
    id: 28,
    title: "Golden Rose",
    price: 299,
    origin: "BD",
    description: dummyText,
    image: "assets/images/14.png",
    color: Color(0xFFAAC585),
  ),
];

String dummyText =
    "A gift is an offering of money or assets made by one person to another in which nothing of comparable value is given, or expected to be given, in return. Some gifts are tax free for both the donor and the recipient, but certain gifts may warrant the payment of taxes.";
